### ISSUE TITLE
Tel links not working with extensions

### ISSUE THREAD

**Issue by mschering** [Intermesh/groupoffice#337]
Customer reported:

So it is not a simple callto-link? It works everywehre on a website when a telephone number is founf. Please try it out, just install the extensions in order to see what I mean: 3CX extension, Zoiper Extension for firefox or chrome - none is working with GO. We really need this. 
And why is opened a new tab everytime I click on a telephone number - this is a new phenomen sonce a few weeks also with my own system.

**Comment by fischli** [comment]
I'm also not satisfied with the current solution. I would prefer a more generic approach. A REST-API would be nice! We are using our own 'click2dial' implementation. All phone numbers are validated on input (inside the addressbook) and where rendered as link to our voip infrastructure. This changed over time (more than once) because of new features inside of our phones (cisco vs. yealink). I would share my code but it dpends on asterisk and yealink phones. Write a comment and i will do my very best to help.

**Comment by mschering** [comment]
The original bug was fixed. In 6.4 you can override go.util.call to whatever your like in a custom module.
