### ISSUE TITLE
Mobile interface display issues

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#343]
There are a few issues in the mobile display, at least on cell-phones. The login page isn't fully in view, you have to scroll right to see it all, and the Account Settings page is also not fitting properly making it almost impossible to use

**Comment by rasos** [comment]
## Login page

The announcement box overlaps the login fields so that no login is possible, if the box has more than four lines on a mobile HD screen, both in portrait or landscape display mode.

Suggested fix: allow the announcement box to be clicked away.

## Calendar

Week view is not possible. 

Suggested fix: allow to hide the overview calendar and reduce the height of the top bar (with search/apps/profile) 

In general, the padding should be reduced at several objets for mobile media.

Tested on Fairphone 2 with GO 6.3.71

**Comment by mschering** [comment]
Hi,

Mobile display is a work in progress. Only notes works for now. We will progress module by module.
I'm closing this for now as it will take a long time to fix.
