### ISSUE TITLE
How to determine host name?

### ISSUE THREAD

**Issue by mschering** [Intermesh/groupoffice#45]
We need to discuss how to determine the full hostname of Group-Office when using cron jobs for example.

**Comment by pvdvendjc** [comment]
Hi Merijn,

I think you not only mean the cronJob but all CLI-actions.
In my opinion the best way to do this is to give it as an argument to the CLI-action
eg. cli.php go.groupoffice.local r=cron/cron

Via a curl request you can get all appropriate settings for this domain (https://go.groupoffice.local/settings/store) and set this (jmap-)response in a session var.

In case of a servermanager installation the cron-job can exec the cli with the correct hostname because this is known in the database.

I have sample codes from other projects if interested. You have my contact details.

Kind regards,
Pieter

**Comment by mschering** [comment]
I've resolved this. The hostname should be stored in the configuration so cron and cli scripts can use it. We should pass the config.ini to the cli scripts.

**Comment by dehart** [comment]
Could we use a relative path to the config.ini? Making it optional to pass the config.ini
