### ISSUE TITLE
About translations of Everyone group name

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#652]
Sorry, I noticed this ticket is closed: Everyone group and all contacts translatable #636 

When you can, pls give some feedback to what I wrote. "my sys admin says its not possible to start modifying directly in the database. as it creates too many headaches, hard to maintain etc. If you can consider doing it directly from the code, Id truely appreciate it. Happy holidays!"

Thanks

**Comment by derjoachim** [comment]
Hi,

Apologies for the late reply. If you haven't already, you can edit the 'Everyone' group from within System Settings. Just be sure to log in as admin and go to System Settings. Click on tab 'Groups' and double click the group named 'Everyone'. 

![image](https://user-images.githubusercontent.com/1264970/122767729-3b389c00-d2a3-11eb-9176-da5988e22e68.png)


There's no manual intervention necessary. You can just edit the group name from within GO itself. Also, please note that this screen shot is taken from within 6.4, but 6.5 will work in a similar way!

If I have somehow misunderstood your issue, please drop us a note. Otherwise, feel free to close this ticket. :-)

**Comment by flaviozluca** [comment]
Friend,

This is about translating Everyone in the GO translation files, not 1 by 1, understand?

It would be much better that way, or else, imagine, each customer has to rename his "Everyone"...

Can you add that string to the translation?

Thanks!
