### ISSUE TITLE
Editing the properties of an email account is impossible

### ISSUE THREAD

**Issue by Lazza** [Intermesh/groupoffice#757]
After adding an external email account and setting up IMAP and SMTP, it seems to work well. However, changing any option is impossible.

When clicking on the "Edit" menu option, the spinner indicates loading for a few seconds, then it aborts with the following message:

> The connection to the server timed out. Please check your internet connection.

While if I do "copy" on the error message, this is copied instead:

> The request timed out. The server took too long to respond. Please try again.

How can we fix this?

The version is v6.5.92, but a similar issue was present with earlier versions as well.

The inbox shows emails correctly and it even notifies when new messages arrive.

**Comment by Lazza** [comment]
Moreover, I have now realized that the _Permissions_ tab is grayed out, therefore I cannot share a IMAP account with other users.

**Comment by derjoachim** [comment]
> The request timed out. The server took too long to respond. Please try again.

Getting a timeout when opening, while still being able to receive email is a bit odd. I am not aware of similar problems elsewhere in the field and I have tried reproducing this behavior on several instances and several imap servers with no success. Is it a commonly used IMAP server like e.g. gmail?

> Moreover, I have now realized that the Permissions tab is grayed out, therefore I cannot share a IMAP account with other users.

In order to fully edit properties of accounts, and specifically  permissions for mailboxes (i.e. share an IMAP accoount), you need to have manage permissions for the email module.

**Comment by mschering** [comment]
Try to check in the developer console which specific request times out and send us the request details. Which parameters and URL.

It also loads sieve filters in the dialog. Maybe it has something todo with that.

**Comment by Lazza** [comment]
Sorry for the long delay but our email tests went down in the queue of priorities. Today we spinned a new VM, installed GroupOffice from scratch with Docker and it seems it's working correctly.

I am going to close this issue. Thank you for your help!
