### ISSUE TITLE
Calendar invites restricted to Adresssbook ?

### ISSUE THREAD

**Issue by pfabrici** [Intermesh/groupoffice#915]
In 6.6.113 we cannot invite attendees to a calendar entry with an email that is not listed in an adressbook. 
If this is configurable somehow can you please give us a hint.
Otherwise this is a feature request :-)

**Comment by gtech99** [comment]
I don't work for Intermesh but I help with code and bug fixes from time to time. I find it quite disrespectful when someone 'requests' features for free into an open source project. If you like the product, great! Please use it as it comes and respect the company's willfulness to provide you with great software at no cost. If you do need extra features, why not offer to pay for it ? It's obviously important to you, and if we all do this, we ensure that a great company such as Intermesh sticks around in order to provide us with software we all use.

I'm not saying Intermesh thinks this, they might even think the opposite, and if so, Merijn, please feel free to remove this comment. 

Here's a rant by someone that explains it better:
https://raccoon.onyxbits.de/blog/bugreport-free-support/

**Comment by pfabrici** [comment]
Hi again,

maybe we have a language misunderstanding here : I assumed that we think that we are doing something wrong and asked politely ( with a "please" ) for help in using this software. For the case that this function is really missing, I raised a "feature request", which is neither a demand or a requirement but a proposal for a new feature, which can be implemented or not.
This was in no way meant disrespectful but constructive in the terms of open source, as the feedback from the community helps making a product better.

@gtech99 : I see your point, but as a paying Intermesh customer, I am astonished to be accused of a freebie mentality here.
@Merijn: thank you for confirming that this is currently not possible, a known issue and not a misconfiguration on our side. Please remove this issue from github if you like, this does not lead to anything.

Regards
Peter
