### ISSUE TITLE
upgrade groupoffice from 6.6.128 -> 6.6.145 -> 6.7.12 error / no login possible

### ISSUE THREAD

**Issue by svenvogel** [Intermesh/groupoffice#961]
Hi Merijn,

since the upgrade to this version i get the following error. install if working fine from any version. db upgrade is always running but after i get always this error in the error.log of the apache webserver. i cant login because i will be always redirected to the https://whatever/install/ screen.

the following error will be produced.
~~~
[Tue Feb 07 17:41:12.495822 2023] [php7:notice] [pid 3758] [client XXX.XXX.XXX.XXX:64805] ErrorException in /mnt/active/www/whatever/htdocs/go/base/util/StringHelper.php at line 1244: mt_srand() expects parameter 1 to be int, float given
~~~

<img width="671" alt="image" src="https://user-images.githubusercontent.com/5433844/217437592-50b67de6-590b-4819-9901-b51318cf969a.png">

i think there is something broken or not correcly replaced?

cheers

Sven

**Comment by derjoachim** [comment]
@svenvogel As per your comment in #907, do I understand correctly that when omitting the `as_float` parameter, you are not getting the error above anymore? Because, if I do omit this in 7.4, I cannot cast it anymore as the return value contains a space. therefore triggering an exception.

If you have SSH access to your server, could you try the following please:

```
root@d6bf39fedb09:/usr/local/share/src# php -a
Interactive shell

php > echo (int) (microtime(true) * 1000000);
```

I would expect the outlook to look like `1675846344021772`, i.e. a fully numeric value. Does the same behavior apply to you?

**Comment by svenvogel** [comment]
@derjoachim 

i tried your command.

~~~
root@cms /root # php -a
Interactive shell

php > echo (int) (microtime(true) * 1000000);
212434478
~~~

i removed the "mt_srand((int) microtime(true) * 1000000);" -> "true" what means microtime dont use "as_float". Yes after that it works.

my final working line is
`mt_srand((int) microtime() * 1000000);`

does this help

**Comment by derjoachim** [comment]
Thanks, but I'm afraid not. If I see your initial error, you were running  PHP 7 (.4?) at the time. I am slightly worried that the code snippet above works differently between instances that run the same version.

Also: `(int) microtime() * 1000000;` returns 0, so mt_srand always gets the same seed. That kinda defeats the purpose of the randomizer.

**Comment by michalcharvat** [comment]
Well this is pretty simple - (int) microtime() just simply convert float 0.xxx to the 0 ...  it does not matter what PHP version you run. Not sure why you do not use my snippet - https://github.com/Intermesh/groupoffice/issues/907#issuecomment-1310973440 . This construct is known since 2012 so I do not think you will create new bike :)

**Comment by derjoachim** [comment]
@michalcharvat I did

**Comment by svenvogel** [comment]
i will test it in the next update and come back.

**Comment by TimWolla** [comment]
Hi! Since PHP 8.2 [I'm listed as a maintainer](https://github.com/php/php-src/blob/d5ce616bb3f7564dbb89155b2b92f686f529959e/EXTENSIONS#L431) for the randomness functionality in PHP. I came across this issue while searching how the new PHP 8.2 `Random\Randomizer` class is used. One of the comments contained the word “Randomizer”, so this popped up in my search.

As this method is documented to generate a password, I **very** strongly recommend using [`\random_int()`](https://www.php.net/manual/en/function.random-int.php) instead of `\mt_rand()`, because the former function uses a cryptographically secure random number generator, whereas the latter does not.

`\mt_rand()` is trivially predictable and this is even more true when you reseed the algorithm before each call by leveraging `\mt_srand()` instead of letting the algorithm do its magic. Any generated password is effectively a function of the current time, which is not exactly a secret value: If I know when the password is generated, I can guess the password with a small number of attempts.

If you can't use `\random_int()`, because your minimum PHP version is less than PHP 7.0 I recommend to raise the minimum version. PHP 7.0 is EOL since quite a long time.

**Comment by derjoachim** [comment]
@TimWolla That is great advice! Thank you! I'll be sure to incorporate this in our currently maintained versions.

**Comment by svenvogel** [comment]
@derjoachim @michalcharvat from my site it seems to be fixed at the moment. i tested the upgrades.
